name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2.4.2

      # Use Node 16.x
      - name: Setup Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16
          cache: "yarn"

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install

      # Create Build
      - name: Create Build
        run: yarn build

      # Archive Package
      - name: Archive Package
        uses: actions/upload-artifact@v3.1.0
        with:
          name: archive
          path: build
